services:
  wedding:
    image: wedding
    networks:
      - npm
      - mariadb
    env_file:
      - ./.env

networks:
  npm:
    external: true
    name: npm
  mariadb:
    external: true
    name: mariadb