services:
  wedding_mariadb:
    image: mariadb:latest
    restart: on-failure
    env_file:
      - ./.env
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    user: '${UID}:${GID}'
    volumes:
      - ./.data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mariadb

  adminer:
    image: adminer:latest
    restart: on-failure
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - npm
      - mariadb

networks:
  npm:
    external: true
    name: npm
  mariadb:
    name: mariadb

